### ISSUE TITLE
Should country output the full country name?

### ISSUE THREAD

**Issue by Tastaturberuf** [oveleon/contao-company-bundle#9]
First, very nice bundle. 

Second, my problem: Should `{{company::country}}` not output the full translated name instead of  `de`?

**Comment by Tastaturberuf** [comment]
I think there can be a new insert tag like `{{company::countrycode}}` or so.

**Comment by zoglo** [comment]
Hello @Tastaturberuf, we've added the new inserttag `{{company::countryname}}` to display the full country name. We've decided not to rewrite `{{company::country}}` to `{{company::countrycode}}` as it might have been used by other people already.

It's available in Version 1.2.8

**Comment by zoglo** [comment]
We went with your solution as country should have shown the full name. It's been rereleased as version 1.2.8

**Comment by Tastaturberuf** [comment]
Thanks so much. Release it as 2.0 for backwards compability.

**Comment by zoglo** [comment]
@Tastaturberuf Sorry for confusing you with our first message. We've discussed it in our team and it was never supposed to display the country-code — that was a bug. The intended behavior was to output the country name and not the code. We did add the new insert-tag if people want to use it in the future.

We suggest that people should use the new `{{company::countrycode}}` insert-tag instead of staying with an older version.
